Web_Store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('supplier.urls')),
    path('', include('users.urls')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
"""Defines URL patterns for store."""

from django.urls import path, include

from . import views

app_name = 'store'

urlpatterns = [
    # Home page
    path('', views.products, name = 'products'),
    # New use registration page.
    path('users/register', views.register, name ='register'),
    # Individual product's page.
    path('<int:pro_id>', views.product, name= 'product'),
    # Product Name By Search Page
    path('store/search/',views.searchByProductName,name='searchByProductName'),
    # Confirm and place order 
    path('store/confirm/<int:pro_id>', views.confirm, name='confirm'),
    # Category Wise Show
    path('store/categorywise/',views.categorywise,name='categorywise'),
    #afterOrderRedirectPage
    path('store/afterOrderRedirect',views.afterOrderRedirect,name='afterOrderRedirect'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Address(models.Model):
    """Address of a user"""
    # This can be changed from OnetoOne to ForignKey if we 
    # want our users to have multiple addresses.
    class Meta:
        verbose_name_plural = "Addresses"

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    addr = models.CharField(verbose_name="address", max_length=150)
    def __str__(self):
        return f"{self.addr[:50]}..."


class Category(models.Model):
    """Category of a product."""
    name = models.CharField(max_length=100, unique=True)
    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    """A product is something user can buy."""
    # set id later on, as of now it added automatically

    name = models.CharField(max_length= 100)
    category = models.ForeignKey(Category, on_delete= models.SET_NULL, null= True )
    description = models.TextField(max_length=2000, null = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    unitprice = models.PositiveIntegerField('Price')
    rem_quant = models.PositiveIntegerField(verbose_name = "quantity remaining")
    image = models.ImageField(upload_to='images', null= True)
    
    def __str__(self):
        """Return a string representtion of the model."""
        return self.name


class Order(models.Model):
    """Stores information about the placed order."""
    user       = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity   = models.PositiveIntegerField()
    product    = models.ForeignKey(Product, on_delete=models.CASCADE)
    date       = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return self.product.name + '_' + str(self.quantity)
 

class Payment(models.Model):
    """Stores information about payment"""
    # Payment is processed by third party, we just keep the data
    # is paid amount redundancy? 
    payed_amount = models.PositiveIntegerField()
    time_stamp = models.DateTimeField(auto_now_add = True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

store/forms.py
from django import forms

from .models import Address, Order

class AddrForm(forms.ModelForm):
    
    class Meta:
        model = Address
        fields = ['addr',]
    
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['quantity', ]

store/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Product, Order
from .forms import AddrForm, OrderForm
from math import ceil

# Create your views here.
@login_required(login_url='users:login')
def confirm(request, pro_id, **kw):
    """Page for confirming the order"""
    if request.method == 'POST':
        form = OrderForm()
        odr = form.save(commit = False)
        odr.quantity = int(request.POST.get('quantity'))
        odr.user = request.user
        product = Product.objects.get(id = pro_id)
        odr.product = product
        if(product.rem_quant - odr.quantity>=0):
            product.rem_quant -= odr.quantity
            product.save() 
            odr.save()
            # Also make an entry of payment
            return render(request, 'store/redirectpage.html')
        else:
            # Redirect to apology
            context = {'required': odr.quantity,'remaining':product.rem_quant,'productid':pro_id}
            return render(request, 'store/outofrange.html', context)
    else:
        product = Product.objects.get(id = pro_id)
        quantity = int(request.GET.get('quantity'))
        if(quantity<=product.rem_quant):
            amount = quantity * product.unitprice
            context = {'product':product, 'amount':amount, 'quantity':quantity}
            return render(request, 'store/confirm.html', context)
        else:
            # Redirect to apology
            context = {'required': quantity,'remaining':product.rem_quant,'productid':pro_id}
            return render(request, 'store/outofrange.html', context)

@login_required(login_url='users:login')
def product(request, pro_id):
    """Page for individual product"""
    product = Product.objects.get(id = pro_id)
    if  request.method != 'POST':
        form = OrderForm()
    
    else:
        form = OrderForm(data = request.POST)
        if form.is_valid():
            odr = form.save(commit = False)
            product = Product.objects.get(id=pro_id)
            if(product.rem_quant - odr.quantity>=0):
                return redirect('store:confirm', pro_id = pro_id)
            
            else:
                # Redirect to apology
                context = {'required': odr.quantity,'remaining':product.rem_quant,'productid':pro_id}
                return render(request, 'store/outofrange.html', context)
            return redirect('store:products')

    context = {"product": product, "form": form}
    return render(request, 'store/product.html', context= context)

def products(request):
    """The home page for store. Show all the products."""
    products = Product.objects.order_by('name')
    context = {'products': products}
    return render(request, 'store/products.html', context)

def register(request):
    """Register a new User"""
    if request.method != 'POST':
        # Display blank registration form.
        form_u = UserCreationForm(prefix= 'user')
        form_a = AddrForm(prefix= 'addr')
    else:
        # Process completed from
        form_u = UserCreationForm(data=request.POST, prefix='user')
        form_a = AddrForm(data=request.POST, prefix= 'addr')
        if form_u.is_valid():
            new_user = form_u.save()
            # Log the new user in and redirect to home page
            login(request, new_user)
            if form_a.is_valid():
                addr = form_a.save(commit=False)
                addr.user = new_user
                addr.save()
            return redirect('store:products')
    # Display a blank or invalid form
    context = {'form_u': form_u, 'form_a': form_a}
    return render(request, 'registration/user_register.html', context)

def searchByProductName(request):
    if request.method == "GET":
        pro_name = request.GET.get('searchquery','')
        products = Product.objects.filter(name__icontains = pro_name)
    return render(request, 'store/search.html',{'products':products,'pro_name':pro_name})

def categorywise(request):
    allProduct = []
    allCategory = Product.objects.values('category','id')
    categories = {item['category'] for item in allCategory}
    for cat in categories:
        prod = Product.objects.filter(category = cat)
        noOfSlide = ((len(prod)//4) + ceil((len(prod)/4)-(len(prod)//4)))
        allProduct.append([prod,range(1,noOfSlide),noOfSlide])

    parameter = {'allProducts':allProduct}
    return render(request,'store/categorywise.html',parameter)

def afterOrderRedirect(request):
    return render(request,'store/redirectpage.html')

store/templates/store/about.html
{% extends 'store/basic.html' %} {% block title %} Pruducts {%endblock title%} {% block body %}

<h1>About us page</h1>

{%endblock%}

store/templates/store/basic.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>

        {% block title %} {% endblock %}
    </title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/store">Web-Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/store">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/store/about">About</a>
                    </li>
                    <span id='loginlogout'>
                      <li class="nav-item">
                        <a class="nav-link" href="/store/login">Login</a>
                      </li>
                    </span>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    {%block body%} {%endblock%}

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->

    {% block script %} {% endblock script %}

</body>

</html>

store/templates/store/categorywise.html
{% extends 'base.html' %}
<!---->

<!---->
{%block body%}
<div class="container">
    <!--Slideshow starts here -->
    
    <br>
    <!---->
    {% for products,range,noOfSlide in allProducts %}
    <b>
        {{forloop.counter}}. <a href="#{{products.0.category}}" style="color:blueviolet;">{{products.0.category}}</a><br>
    </b>
    <!---->
    {%endfor%}
    <!---->
    {% for products,range,noOfSlide in allProducts %}

    <div id="{{products.0.category}}">
        <h1 class="my-4">{{products.0.category}}</h1>
        <div class="row">
            <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
                <ul class="carousel-indicators">
                    <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>
                    {% for i in range %}
                    <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
                    {% endfor %}
                </ul>

                <!--Slideshow starts here -->

                <div class="container carousel-inner no-padding">

                    <div class="carousel-item active">

                        {% for i in products %}
                        <div class="col-xs-3 col-sm-3 col-md-3">
                            <div class="card" style="width: 18rem;">
                                <img src="{{i.image.url}}" class="card-img-top" alt="{{i.name}} image">
                                <div class="card-body">
                                    <h5 class="card-title">{{i.name}}</h5>
                                    <h5 class="card-title">Only &#x20B9;{{i.unitprice}}</h5>
                                    {% if i.rem_quant %}
                                    <h5 class="card-title">Only {{i.rem_quant}} Piece Left</h5>
                                    {% else %}
                                    <h5 class="card-title">Out Of Stock</h5>
                                    {% endif %}
                                    <p class="card-text">{{i.description|slice:"0:50"}} ...</p>
                                    <a href="{% url 'store:product' i.id %}" class="btn btn-primary">CheckOut</a>
                                    <a href="{% url 'store:product' i.id %}" class="btn btn-primary">Buy</a>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
                    </div>
                    <div class="carousel-item">
                        {% endif %}
                        <!---->
                        {% endfor %}
                    </div>

                </div>
            </div>

            <!-- left and right controls for the slide -->

            <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{%endblock%}

store/templates/store/confirm.html
{% extends 'base.html' %}
<!---->
{%block body%}
<div>
    <div class="card text-center">
        <b>  
      <div class="card-header">
            Confirm Your Oder
        </div>
      </b>
        <div class="card-body">
            <h5 class="card-title">Name : {{product}}</h5>
            <h5 class="card-title">Quantity : {{quantity}}</h5>
            <h5 class="card-title">Price : {{product.unitprice}}</h5>
            <h5 class="card-title">Net Total : {{amount}}</h5>

            <form prefix='confirmation' action='{% url "store:confirm" product.id %}' method='post'>
                {% csrf_token %}
                <input type='submit' class="btn btn-success" value='Pay Securly'>
                <input type='hidden' name='quantity' value={{quantity}}>
            </form>
            <form action='{% url "store:products" %}' method='get'>
                <input type='submit' class="btn btn-danger" value='Cancel'>
            </form>
        </div>
        <div class="card-footer text-muted">
            Thank You
        </div>
    </div>
</div>
<!--
<p> Confirm You Oder </p>
{{product}} - {{product.unitprice}} Rs.- quantity : {{quantity}} - Pirce you pay: {{amount}} Rs.

<h1></h1>
<form prefix='confirmation' action='{% url "store:confirm" product.id %}' method='post'>
    {% csrf_token %}
    <input type='submit' value='Pay Securly'>
    <input type='hidden' name='quantity' value={{quantity}}>
</form>
<form action='{% url "store:products" %}' method='get'>
    <input type='submit' value='cancel'>
</form>
<h1>{{order.user}}</h1>
-->
{%endblock%}

store/templates/store/index.html
{% extends 'store/basic.html' %} {% block title %} Pruducts {%endblock title%} {% block body %}

<h1>Product Page</h1>

{%endblock%}

store/templates/store/login.html
{% extends 'store/basic.html' %} {% block title %} Pruducts {%endblock title%} {% block body %}

<h1>Login Page</h1>

{%endblock%}

store/templates/store/outofrange.html
{% extends 'base.html' %}
<!---->
{%block body%}
<div style="align-items: center;">
    <P>Sorry For Inconvenience </P>
    <p>We only have left with only {{remaining}} piece and you want {{required}} piece</P>
    <p>if {{remaining}} piece would be okk then <a href="{% url 'store:product' productid %}">click here</a> or for more product go to home</p>
</div>
{%endblock%}

store/templates/store/product.html
{% extends 'base.html' %}
<!---->
{%block body%}


<div class="container my-4">
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                {{ product.img_obj}}
                <img src={{product.image.url}}>
            </div>
        </div>
        <div class="col-md-8">
            <h2>{{product.name}}</h2>
            <h5>Seller : {{product.owner}}</h5>
            <h5>Price : {{product.unitprice}}</h5>
            <h6>Description : {{product.description}}</h6>

            {% if product.rem_quant %}
            <h5>Unit Remaining : {{product.rem_quant}}</h5>
            {% else %}
            <h5>Out Of Stock</h5>
            {% endif %}

            <br> {% if product.rem_quant %}
            <form method=GET action="{% url 'store:confirm' product.id %}">
                {% csrf_token %}
                <!---->
                {{ form.as_p}}
                <!---->
                <button class="btn btn-primary" name="placeordersubmit"> Place order</button>
                <input type='hidden' name='next' value='store:products'>
                <form>
                    {%else%}
                    <h5> Stay Tuned For Next Stok :) </h5>
                    {%endif%}
        </div>
    </div>
</div>

{%endblock%}

store/templates/store/products.html
{% extends 'base.html' %}
<!---->

<!---->
{%block body%}

<div class="productview" style="margin: 32px;">
    {% for product in products %}
    <div class="col-xs-3 col-sm-3 col-md-3">
        <div class="card" style="width: 18rem;">
            <img src="{{product.image.url}}" class="card-img-top" alt="{{prduct.name}} image">
            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <h5 class="card-title">Only &#x20B9;{{product.unitprice}}</h5>
                {% if product.rem_quant %}
                <!--<h5 class="card-title">Only {{product.rem_quant}} Piece Left</h5>-->
                {% else %}
                <h5 class="card-title">Out Of Stock</h5>
                {% endif %}
                <p class="card-text">{{product.description|slice:"0:50"}} ...</p>
                <a href="{% url 'store:product' product.id %}" class="btn btn-primary">CheckOut</a>
                <a href="{% url 'store:product' product.id %}" class="btn btn-primary">Buy</a>
            </div>
        </div>
    </div>
    <!---->
    {% empty %}
    <li>No products have been added yet.</li>
    {% endfor %}
    <!---->
</div>
{%endblock%}

store/templates/store/redirectpage.html
{% extends 'base.html' %}
<!---->
{%block body%}
<!---->
<div class="text-center">
    <h3>Thank You For Shoping</h3>
    <h6>You Will Redirect To Main Page Whithin
        <span id="counter">5</span> Second </h6>
    <i>or</i>
    <h6><a href="{% url 'store:products' %}">Click Here To Redirect Now</a></h6>
</div>

<script>
    setInterval(function() {
        var div = document.querySelector("#counter");
        var count = div.textContent * 1 - 1;
        div.textContent = count;
        if (count <= 0) {
            window.location = '{% url "store:products" %}';
        }
    }, 1000);
</script>

{%endblock%}

store/templates/store/registration.html
{% extends 'store/basic.html' %} {% block title %} Pruducts {%endblock title%} {% block body %}

<h1>User Registartion page</h1>

{%endblock%}

store/templates/store/search.html
{% extends 'base.html' %}
<!---->
{%block body%}


<b>Search For Product: {{pro_name}}</b><br>
<b><a href="{% url 'store:products' %}">Clear Search</a></b>

<div class="productview" style="margin: 32px;">
    {% for product in products %}
    <div class="col-xs-3 col-sm-3 col-md-3">
        <div class="card" style="width: 18rem;">
            <img src="{{product.image.url}}" class="card-img-top" alt="{{prduct.name}} image">
            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <h5 class="card-title">Only &#x20B9;{{product.unitprice}}</h5>
                {% if product.rem_quant %}
                <h5 class="card-title">Only {{product.rem_quant}} Piece Left</h5>
                {% else %}
                <h5 class="card-title">Out Of Stock</h5>
                {% endif %}
                <p class="card-text">{{product.description|slice:"0:50"}} ...</p>
                <a href="{% url 'store:product' product.id %}" class="btn btn-primary">CheckOut</a>
                <a href="{% url 'store:product' product.id %}" class="btn btn-primary">Buy</a>
            </div>
        </div>
    </div>
    <!---->
    {% empty %}
    <li>Not Found Product With Product Name {{pro_name}}</li>
    {% endfor %}
    <!---->
    {%endblock%}
</div>