Web_Store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('supplier.urls')),
    path('', include('users.urls')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
"""Defines URL patterns for store."""

from django.urls import path, include

from . import views

app_name = 'store'

urlpatterns = [
    # Home page
    path('', views.products, name = 'products'),
    # New use registration page.
    path('users/register', views.register, name ='register'),
    # Individual product's page.
    path('<int:pro_id>', views.product, name= 'product'),
    # Product Name By Search Page
    path('store/search/',views.searchByProductName,name='searchByProductName'),
    # Confirm and place order 
    path('store/confirm/<int:pro_id>', views.confirm, name='confirm'),
    # Category Wise Show
    path('store/categorywise/',views.categorywise,name='categorywise'),
    #afterOrderRedirectPage
    path('store/afterOrderRedirect',views.afterOrderRedirect,name='afterOrderRedirect'),
]

users/urls.py
"""Urls for users app"""

from django.urls import path, include

from .import views
app_name = "users"

urlpatterns = [
    # Include default auth urls.
    path('users/', include('django.contrib.auth.urls')),
    # Url for redirect page.
    path('users/', views.redirects, name = 'redirects'),
    # Let user see his details
    path('users/details', views.details, name = 'details'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.db.models import F
from store.models import Product,Address,Order
from django.contrib.auth.decorators import login_required

# Create your views here.

def redirects(request):
    """Redirects  user to apropriate page after log in."""
    if(request.user.has_perm('auth.can_sell')):
        return redirect('supplier:products')
    else:
        return redirect('store:products')

@login_required(login_url= 'users:login')
def details(request):
    """Allows user to see his details and order history"""
    if request.method == 'POST':
        sortingmethod = request.POST.get('sortingmethod','')
        sortingOrder = request.POST.get('sortingOrder','')
        addr = Address.objects.get(user = request.user)
        if(sortingmethod=='Alphabatical Order Of Product Name'):
            if(sortingOrder=='Ascending'):
                odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by('product__name')      
            else:
                sortingOrder = "Descending"
                odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by('-product__name')
        elif(sortingmethod=='Amount Payed'):
            if(sortingOrder=='Ascending'):
                odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by(F('product__unitprice')*F('quantity'))      
            else:
                sortingOrder = "Descending"
                odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by(-F('product__unitprice')*F('quantity'))
        elif(sortingmethod=='Order Time'):
            if(sortingOrder=='Ascending'):
                odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by('date')      
            else:
                sortingOrder = "Descending"
                odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by('-date')
        else:
            sortingmethod = "Order Time"
            sortingOrder = "Descending"
            odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by('date')
        context = {'address': addr, 'orders':odrs,'sortingmethod':sortingmethod,'sortingOrder':sortingOrder}
        return render(request, 'users/details.html', context)
    else:
        sortingmethod = "Order Time"
        sortingOrder = "Ascending"
        addr = Address.objects.get(user = request.user)
        odrs = Order.objects.filter(user = request.user).values('product__name', 'quantity', 'product__unitprice', 'date').order_by('date')
        context = {'address': addr, 'orders':odrs,'sortingmethod':sortingmethod,'sortingOrder':sortingOrder}
        return render(request, 'users/details.html', context)

    

users/templates/users/details.html
{% extends 'base.html' %}
<!---->
{%block body%}
<h3> Hey, {{ user.username}}</h3>
<h5> Your Registered Address : {{address.addr}}</h4>
    <br>
    <form action="{% url 'users:details' %}" method="POST">
        {% csrf_token %}
        <label for="sortingmethod">Choose Sorting Method : </label>
        <select name="sortingmethod" id="sortingmethod">
            <option value="Order Time" selected>Order Time</option>
            <option value="Alphabatical Order Of Product Name">Alphabatical Order Of Product Name</option>
            <option value="Amount Payed">Amount Payed</option>
          </select>
        <br><br>

        <label for="sortingOrder">Choose Sorting Order : </label>
        <div class="form-check form-check-inline">
            <input class="form-check-input" name="sortingOrder" type="radio" id="Ascending" value="Ascending">
            <label class="form-check-label" for="Ascending">Ascending</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" name="sortingOrder" type="radio" id="Descending" value="Descending">
            <label class="form-check-label" for="Descending">Descending</label>
        </div>

        <button type="submit" name="submit" id="submit" value="submit">Submit</button>

    </form>
    <br>
    <h5>
        Table with {{sortingmethod}} In {{sortingOrder}} Order
    </h5>
    <table class=" table table-hover table-bordered border-primary ">
        <thead>
            <tr>
                <th scope="row ">No.</th>
                <td>Product Name</td>
                <td>Quantity</td>
                <td>UnitPrice</td>
                <td>Total</td>
                <td>Date</td>
            </tr>
        </thead>
        <tbody>
            {% for o in orders %}
            <tr>
                <th scope="row ">{{forloop.counter}}</th>
                <td>{{o.product__name}}</td>
                <td>{{o.quantity }}</td>
                <td>{{o.product__unitprice}}</td>
                <td>{% widthratio o.quantity 1 o.product__unitprice %}</td>
                <td>{{o.date}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        console.log("AJAY")
    </script>
    {%endblock%}