Web_Store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('supplier.urls')),
    path('', include('users.urls')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
"""Defines URL patterns for store."""

from django.urls import path, include

from . import views

app_name = 'store'

urlpatterns = [
    # Home page
    path('', views.products, name = 'products'),
    # New use registration page.
    path('users/register', views.register, name ='register'),
    # Individual product's page.
    path('<int:pro_id>', views.product, name= 'product'),
    # Product Name By Search Page
    path('store/search/',views.searchByProductName,name='searchByProductName'),
    # Confirm and place order 
    path('store/confirm/<int:pro_id>', views.confirm, name='confirm'),
    # Category Wise Show
    path('store/categorywise/',views.categorywise,name='categorywise'),
    #afterOrderRedirectPage
    path('store/afterOrderRedirect',views.afterOrderRedirect,name='afterOrderRedirect'),
]

supplier/urls.py
"""Defines URL patterns for supplier."""

from django.urls import path, include

from .import views

app_name = 'supplier'

urlpatterns = [
    # Home page
    path('supplier/', views.products, name = 'products'),
    # Page for adding a new product
    path('supplier/new_product', views.new_product, name = 'new_product'),
    # New supplier registration
    path('supplier/register', views.register, name = 'register'),
    # Edit the product
    path('edit_pro/<int:pro_id>/', views.edit_pro, name = 'edit_pro'),
    # Supplier can see details of his produt
    path('supplier/product/<int:pro_id>/', views.product, name = 'product'),
    # All orders that the suppllier has got for his product
    path('supplier/orders', views.orders, name= 'orders')
]

supplier/forms.py
from django import forms

from store.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name', 
            'category', 
            'unitprice', 
            'rem_quant', 
            'description',
            'image',
        ]
        labels = {
            'name': 'Product Name',
        }

supplier/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import Permission
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count, Sum
from django.views.decorators.csrf import csrf_exempt
from store.forms  import AddrForm
from store.models import Product
from store.models import Order
from .forms import ProductForm
from django.http import Http404


# Make a diffrent page for exitsing seller to become seller 
@permission_required('auth.can_sell', login_url='supplier:register')
def products(request):
    """The home page for store. Show all the products."""
    products = Product.objects.filter(owner=request.user).order_by('name')
    context = {'products': products}
    #print(pro)
    return render(request, 'supplier/products.html', context)

@permission_required('auth.can_sell', login_url='supplier:register')
def new_product(request):
    """Add a ner Product."""
    if request.method != 'POST':
        # No data submitted; create blank from.
        form = ProductForm()

    else:
        # POST data submitted; process data.
        form = ProductForm(request.POST, request.FILES)
        
        if form.is_valid():
            new_prod = form.save(commit=False)
            new_prod.owner = request.user
            new_prod.save()
            return redirect('supplier:products')

    # Display a blan or invalid form.
    context = { 'form': form}
    return render(request, 'supplier/new_product.html', context)


def register(request):
    """Register a new Seller"""
    if request.method != 'POST':
        # Display blank registration form.
        form_u = UserCreationForm(prefix = 'user')
        form_a = AddrForm( prefix = 'addr')
        #print(form_a)
    else:
        # Process completed from
        form_u= UserCreationForm(data=request.POST, prefix = 'user')
        form_a = AddrForm(data = request.POST, prefix = 'addr')

        if form_u.is_valid():
            new_user = form_u.save()
            permission = Permission.objects.get(codename='can_sell')
            new_user.user_permissions.add(permission)
            # Log the new user in and redirect to home page
            if form_a.is_valid():
                #print("yes")
                addr = form_a.save(commit=False)
                addr.user = new_user
                addr.save()                
            login(request, new_user)
            return redirect('users:redirects')
    # Display a blank or invalid form
    context = {'form_u': form_u, 'form_a':form_a}
    return render(request, 'registration/supplier_register.html', context)

@permission_required('auth.can_sell', login_url='supplier:register')
def product(request, pro_id):
    """Seller can see details of their product"""
    product = Product.objects.get( id = pro_id)

    # Make sure product belongs to the current supplier
    if product.owner != request.user:
        raise Http404("404")
    
    return render(request, 'supplier/product.html', {'product':product})

@permission_required('auth.can_sell', login_url='supplier:register')
def edit_pro(request, pro_id):
    '''Edit existing product'''
    product = Product.objects.get( id = pro_id)
   

    if product.owner != request.user:
       raise Http404
    
    if request.method != 'POST':
        # Initial request; pre-fill form with detais
        form = ProductForm(instance = product)

    else:
        # POST data submitted; process data.
        form = ProductForm( instance = product, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('supplier:product', pro_id = pro_id)

    return render(request, 'supplier/edit_pro.html', {'form':form, 'product':product})


@permission_required('auth.can_sell', login_url='supplier:register')
def orders(request):
    user = request.user
    odrs = Order.objects.filter(product__owner = user).values('product__name').annotate(Sum('quantity'))
    totalProductSold = 0
    for o in odrs:
        totalProductSold += o['quantity__sum']
    return render(request, 'supplier/orders.html', {'orders': odrs,'totalProductSold':totalProductSold})

supplier/templates/supplier/edit_pro.html
{% extends 'base.html' %}
<!---->
{%block body%}

<div class="container my-4">
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                {{ product.img_obj}}
                <img src={{product.image.url}}>
            </div>
        </div>
        <div class="col-md-8">
            <form class='card-title' action="{% url 'supplier:edit_pro' product.id %}" method='post'>
                {% csrf_token %} {{form.as_p}}
                <button name="submit"> Save changes</button>
            </form>
        </div>
    </div>
</div>

{%endblock%}

supplier/templates/supplier/new_product.html
{% extends 'base.html' %}
<!---->
{%block body%}

<div>
    <div class="card " style="margin-left: 20%;margin-right: 20%;">
        <b>  
      <div class="card-header text-center">
        Add a new product
        </div>
      </b>
        <div class="card-body">
            <form enctype="multipart/form-data" action="{% url 'supplier:new_product' %}" method='post'>
                {% csrf_token %} {{form.as_p}}
                <button class="btn btn-primary" name="submit"> Add product</button>

            </form>

        </div>
    </div>
</div>

<!---->
{%endblock%}

supplier/templates/supplier/orders.html
{% extends 'base.html' %}
<!---->
{%block body%}
<!---->
<h3> Hey, {{ user.username}} </h3>
<!---->
<h5>You Sold Total <b>{{totalProductSold}}</b> Product </h5>
<p>The Details Are as follow ...</p>
<table class="table table-hover table-bordered border-primary " style="width: auto;">
    <thead>
        <tr>
            <th scope="row">No.</th>
            <td>Product Name</td>
            <td>Quantity</td>
        </tr>
    </thead>
    <tbody>
        {% for o in orders %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{o.product__name}}</td>
            <td>{{o.quantity__sum}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!---->
{%endblock%}

supplier/templates/supplier/product.html
{% extends 'base.html' %}
<!---->
{%block body%}

<div class="container my-4">
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                {{product.img_obj}}
                <img src={{product.image.url}}>
            </div>
        </div>
        <div class="col-md-8">
            <h2>{{product.name}}</h2>
            <h5>Seller : {{product.owner}}</h5>
            <h5>Price : {{product.unitprice}}</h5>
            <h5>Unit Remaining : {{product.rem_quant}}</h5>
            <h6>Product Description: {{ product.description }}</h6>
            <br>
            <a href="{% url 'supplier:edit_pro' product.id %}"> Edit </a>
        </div>
    </div>
</div>
{%endblock%}

supplier/templates/supplier/products.html
{% extends 'base.html' %}
<!---->
{%block body%}
<a class="btn btn-primary" href="{% url 'supplier:new_product' %}">Add a new product</a>
<a class="btn btn-primary" href='{% url "supplier:orders" %}'> All orders </a>
<br>
<br>
<!---->

{% if products %}
<h4>Your Listed Products</h4>
<table class="table table-hover table-bordered " style="width: auto;">
    <thead>
        <tr>
            <th scope="row">No.</th>
            <td>Product Name</td>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'supplier:product' product.id %}">{{ product.name}}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h4> You have nothing added to sell </h4>
{% endif%} {%endblock%}